version: "3.4"

services:
  ib-gateway-service:
    container_name: ib-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      NODE_ENV: production
    ports:
      - 4001:4001
      - 4002:4002
